### ISSUE TITLE
Great Theme, but heres some minor issues

### ISSUE THREAD

**Issue by Godz-hi** [leeprky/Ovel#2]
![image](https://user-images.githubusercontent.com/53191186/122792759-737eb100-d288-11eb-9215-b4c7ec9a915b.png)
^^^ As show above my numbers at the end of my name arent with my username at the top of the screen and that makes a big random space just for those numbers.

![image](https://user-images.githubusercontent.com/53191186/122795970-de7db700-d28b-11eb-8916-8874275af9f0.png)
^^^ The text box being a bit bigger than usual is most likely because of the 4 numbers thing still being there when it shouldn't be, but gonna put it here anyway.

![image](https://user-images.githubusercontent.com/53191186/122792909-97da8d80-d288-11eb-9699-a97917347369.png)
^^^ Buttons are all over the place on the my account screen.

![image](https://user-images.githubusercontent.com/53191186/122793038-bd679700-d288-11eb-88cd-8356e40b0faf.png)
^^^ Transaction history doesn't match the theme.

![image](https://user-images.githubusercontent.com/53191186/122793558-58f90780-d289-11eb-8c2a-3d86a8e19f2a.png)
^^^ Not sure if this intentional, doesn't look bad but there is just a random bar at the top of the settings menu.

![image](https://user-images.githubusercontent.com/53191186/122793678-7af28a00-d289-11eb-996c-3ebf77352a7f.png)
^^^ When you have multiple people in a channel and turn on the Show Voice Users thing by right-clicking the channel name in the bottom left, the PFPS of each user are spaced out very oddly.

![image](https://user-images.githubusercontent.com/53191186/122793925-b68d5400-d289-11eb-8965-2fb431c46dd0.png)
^^^ The text of when someone is talking seems a little too dark, in my opinion, may just be me though, but could lead to issues to people with monitors that can't distinguish these colors.

![image](https://user-images.githubusercontent.com/53191186/122794700-898d7100-d28a-11eb-9c74-877868e85218.png)
^^^ Complete a few steps, thing doesn't fit all of screen!

![image](https://user-images.githubusercontent.com/53191186/122795423-4da6db80-d28b-11eb-88bc-ab85d6db1859.png)
^^^ Buttons smaller than sub-section texts, looks odd.

![image](https://user-images.githubusercontent.com/53191186/122795543-7038f480-d28b-11eb-81d7-289dc320c49b.png)
^^^ Server searching popup is in wrong position.

![image](https://user-images.githubusercontent.com/53191186/122795610-7f1fa700-d28b-11eb-8ce7-36d17f9b55d3.png)
^^^ Space where search used to be is still there so it looks kinda weird, maybe intentional though. 

![image](https://user-images.githubusercontent.com/53191186/122796439-6237a380-d28c-11eb-963c-23429f132a46.png)
^^^ List of all my plugins if you think any of these could be causing it!

Thanks, Also an awesome theme! If you have any questions about the issues (or features) lemme know!

Also sorry if any of these are already known I just joined the discord and saw some, but just gonna leave them in here anyway.

**Comment by leeprky** [comment]
Thanks For The Issues!

#1 I Assume this is a plugin since this isnt the case for me

#2 Updated Already & Fixed

#3 Updated Already & Fixed

#4 I Dont have a transaction so if u get the css for the background of that i can theme it for you!

#5 Thats the drag the window

#6 I dunno

#7 Happens when in fullscreen + discord thing

#8 Intentional to be aligned better#1 

Thanks!

**Comment by Godz-hi** [comment]
Payment Stuff
![image](https://user-images.githubusercontent.com/53191186/122800583-1a674b00-d291-11eb-8e53-acdf84312ce5.png)


.theme-dark .paymentPane-3bwJ6A changes border around rows of payments
![image](https://user-images.githubusercontent.com/53191186/122801212-d32d8a00-d291-11eb-8139-41e2e7970299.png)

.theme-dark .payment-xT17Mq changes each row of payments
![image](https://user-images.githubusercontent.com/53191186/122801325-f5bfa300-d291-11eb-8380-b7fe353087e6.png)

.theme-dark .expandedInfo-3kfShd changes the info that shows when you click on a payment
![image](https://user-images.githubusercontent.com/53191186/122801623-5e0e8480-d292-11eb-83be-74137ba7b62c.png)

Then there is also small dividers between each payment, here's the css property for it: 
.theme-dark .bottomDivider-1K9Gao

If you need any other css stuff lemme know and once you add it to the theme I can make sure everything looks good!

**Comment by leeprky** [comment]
[class="paymentHistory-2FXzro"] {
    background-color: var(--background-tertiary);
  }
might have done it
