### ISSUE TITLE
Member List being cut off by theme

### ISSUE THREAD

**Issue by MintLily** [leeprky/Ovel#3]
The member list is cut off by the theme, mainly when there are not many users in a server or group chat.

Image:
![Preview](https://kortyboi.com/img/upload/6TuYI1TDxB.gif)

BetterDiscord (Current)
Powercord (unknown, untested - Canary is completely broken for me, crashes on start up)

**Comment by leeprky** [comment]
![image](https://user-images.githubusercontent.com/71296232/124251887-5070be80-db1e-11eb-9a57-a0fb03227d84.png)
 ?

**Comment by MintLily** [comment]
Longer user lists seem to be fine. It might only show up as being cutoff when there are not that many users in the list.
